/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintRouteImport } from './routes/print'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardTabelaPrecosRouteImport } from './routes/dashboard/tabela-precos'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardFinanceiroRouteImport } from './routes/dashboard/financeiro'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard/agenda'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardPacientesIndexRouteImport } from './routes/dashboard/pacientes/index'
import { Route as PrintReceiptInvoiceIdRouteImport } from './routes/print/receipt/$invoiceId'
import { Route as PrintInvoiceInvoiceIdRouteImport } from './routes/print/invoice/$invoiceId'
import { Route as DashboardPacientesPatientIdRouteImport } from './routes/dashboard/pacientes/$patientId'

const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTabelaPrecosRoute = DashboardTabelaPrecosRouteImport.update({
  id: '/tabela-precos',
  path: '/tabela-precos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceiroRoute = DashboardFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPacientesIndexRoute = DashboardPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => DashboardRoute,
} as any)
const PrintReceiptInvoiceIdRoute = PrintReceiptInvoiceIdRouteImport.update({
  id: '/receipt/$invoiceId',
  path: '/receipt/$invoiceId',
  getParentRoute: () => PrintRoute,
} as any)
const PrintInvoiceInvoiceIdRoute = PrintInvoiceInvoiceIdRouteImport.update({
  id: '/invoice/$invoiceId',
  path: '/invoice/$invoiceId',
  getParentRoute: () => PrintRoute,
} as any)
const DashboardPacientesPatientIdRoute =
  DashboardPacientesPatientIdRouteImport.update({
    id: '/pacientes/$patientId',
    path: '/pacientes/$patientId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tabela-precos': typeof DashboardTabelaPrecosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pacientes/$patientId': typeof DashboardPacientesPatientIdRoute
  '/print/invoice/$invoiceId': typeof PrintInvoiceInvoiceIdRoute
  '/print/receipt/$invoiceId': typeof PrintReceiptInvoiceIdRoute
  '/dashboard/pacientes': typeof DashboardPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tabela-precos': typeof DashboardTabelaPrecosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pacientes/$patientId': typeof DashboardPacientesPatientIdRoute
  '/print/invoice/$invoiceId': typeof PrintInvoiceInvoiceIdRoute
  '/print/receipt/$invoiceId': typeof PrintReceiptInvoiceIdRoute
  '/dashboard/pacientes': typeof DashboardPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tabela-precos': typeof DashboardTabelaPrecosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pacientes/$patientId': typeof DashboardPacientesPatientIdRoute
  '/print/invoice/$invoiceId': typeof PrintInvoiceInvoiceIdRoute
  '/print/receipt/$invoiceId': typeof PrintReceiptInvoiceIdRoute
  '/dashboard/pacientes/': typeof DashboardPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/print'
    | '/api/$'
    | '/dashboard/agenda'
    | '/dashboard/financeiro'
    | '/dashboard/settings'
    | '/dashboard/tabela-precos'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/pacientes/$patientId'
    | '/print/invoice/$invoiceId'
    | '/print/receipt/$invoiceId'
    | '/dashboard/pacientes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/print'
    | '/api/$'
    | '/dashboard/agenda'
    | '/dashboard/financeiro'
    | '/dashboard/settings'
    | '/dashboard/tabela-precos'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/pacientes/$patientId'
    | '/print/invoice/$invoiceId'
    | '/print/receipt/$invoiceId'
    | '/dashboard/pacientes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/print'
    | '/api/$'
    | '/dashboard/agenda'
    | '/dashboard/financeiro'
    | '/dashboard/settings'
    | '/dashboard/tabela-precos'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/pacientes/$patientId'
    | '/print/invoice/$invoiceId'
    | '/print/receipt/$invoiceId'
    | '/dashboard/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrintRoute: typeof PrintRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tabela-precos': {
      id: '/dashboard/tabela-precos'
      path: '/tabela-precos'
      fullPath: '/dashboard/tabela-precos'
      preLoaderRoute: typeof DashboardTabelaPrecosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/financeiro': {
      id: '/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof DashboardFinanceiroRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pacientes/': {
      id: '/dashboard/pacientes/'
      path: '/pacientes'
      fullPath: '/dashboard/pacientes'
      preLoaderRoute: typeof DashboardPacientesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/print/receipt/$invoiceId': {
      id: '/print/receipt/$invoiceId'
      path: '/receipt/$invoiceId'
      fullPath: '/print/receipt/$invoiceId'
      preLoaderRoute: typeof PrintReceiptInvoiceIdRouteImport
      parentRoute: typeof PrintRoute
    }
    '/print/invoice/$invoiceId': {
      id: '/print/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/print/invoice/$invoiceId'
      preLoaderRoute: typeof PrintInvoiceInvoiceIdRouteImport
      parentRoute: typeof PrintRoute
    }
    '/dashboard/pacientes/$patientId': {
      id: '/dashboard/pacientes/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/dashboard/pacientes/$patientId'
      preLoaderRoute: typeof DashboardPacientesPatientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardFinanceiroRoute: typeof DashboardFinanceiroRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTabelaPrecosRoute: typeof DashboardTabelaPrecosRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPacientesPatientIdRoute: typeof DashboardPacientesPatientIdRoute
  DashboardPacientesIndexRoute: typeof DashboardPacientesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardFinanceiroRoute: DashboardFinanceiroRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTabelaPrecosRoute: DashboardTabelaPrecosRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPacientesPatientIdRoute: DashboardPacientesPatientIdRoute,
  DashboardPacientesIndexRoute: DashboardPacientesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PrintRouteChildren {
  PrintInvoiceInvoiceIdRoute: typeof PrintInvoiceInvoiceIdRoute
  PrintReceiptInvoiceIdRoute: typeof PrintReceiptInvoiceIdRoute
}

const PrintRouteChildren: PrintRouteChildren = {
  PrintInvoiceInvoiceIdRoute: PrintInvoiceInvoiceIdRoute,
  PrintReceiptInvoiceIdRoute: PrintReceiptInvoiceIdRoute,
}

const PrintRouteWithChildren = PrintRoute._addFileChildren(PrintRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrintRoute: PrintRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
